name: Eyuel Berga Woldemichael
title: Full-Stack Software Developer
summary: Full-Stack Software Developer with a passion for writinga 
social:
  linkedin: eyuelberga
  medium: eyuelberga
  dev.to: eyuelberga
  twitter: eyuelbergaw
  github: eyuelberga
  website: https://eyuelberga.github.io
skills:
  languages:
    - JavaScript: advanced
    - TypeScript: advanced
    - Python: medium
    - Java: medium
    - Golang: beginner
    - C: beginner
  frameworks:
    - Vue.js: advanced
    - React: advanced
    - Node.js: medium
    - Django: medium
    - NestJs: beginner
    - Hasura: advanced
  tools:
    - Git: advanced
    - Docker: medium
    - Github Actions: medium
    - Tmux: beginner
    - NeoVim: beginner
  databases:
    - PostgreSQL: medium
    - Mongodb: medium
    - Firestore: medium
education:
  - institution: Addis Ababa University
    study: Bsc. Software Engineering
    location: "Addis Ababa, Ethiopia"
    start: "September, 2016"
    end: "October, 2021"
    gpa: 3.57
    description:
      - One of the top universities in Africa
      - Graduated with Great Distniction 
projects:
  - name: Peer Notes
    repo: peernotes
    description: A web application for High School students to share school notes with other peers
    banner:
      branch: main
      path: assets/banner.png
    tech:
      - Hasura
      - React
      - Auth0
      - Algolia
      - Docker
      - Github Actions
      - GraphQL
  - name: Keywrite
    repo: keywrite
    description: A Javascript library for creating custom input methods for typing non-latin scripts on standard keyboard
    banner:
      branch: main
      path: logo/banner.png
    tech:
      - TypeScript
      - Yarn Workspace
      - Lerna
      - Github Actions
  - name: School Location Analysis Tool
    repo: gis-school-analysis-tool
    description: a GIS application to locate potential locations for public school construction in the city of Addis Ababa, Ethiopia.
    banner:
      branch: master
      path: banner.png
    tech:
      - GeoDjango
      - PostGIS
      - Bootstrap
      - LeafletJs
      - Heroku
      - Docker
  - name: Pic Share
    repo: pic-share
    description: WebRTC based P2P image sharing web application
    banner:
      branch: master
      path: img/banner.png
    tech:
      - WebRTC
      - React
      - NodeJs
  - name: Amharic Proverbs
    repo: AmharicProverbs
    description: Web appication to access Amharic proverbs from the Amharic Proverbs API
    banner:
      branch: main
      path: banner.png
    tech:
      - Vue3
      - Bootstrap
      - Vite
      - REST API
  - name:  Kesar Cipher
    repo: KesarCipher
    description: Implementation of the Caesar Cipher encryption algorithm that works with the Ge'ez Alphabet
    banner:
      branch: main
      path: banner.png
    tech:
      - JavaScript
      - Vite
      - Tailwind CSS
  - name:  Amharic Proverbs API
    repo: AmharicProverbsAPI
    description: API for accessing a growing list of Amharic Proverbs
    banner:
      branch: main
      path: banner.png
    tech:
      - NestJs
      - Mongodb
      - Heroku
