name: Eyuel Berga Woldemichael
title: Full-Stack Software Developer
summary: Hi there! I'm Eyuel, a Software Developer currently based in the US.
social:
  linkedin: eyuelberga
  medium: eyuelberga
  dev.to: eyuelberga
  twitter: eyuelbergaw
  github: eyuelberga
  website: https://eyuelberga.github.io
skills:
  languages:
    - JavaScript: advanced
    - TypeScript: advanced
    - Python: medium
    - Java: medium
    - Golang: beginner
    - C: beginner
  frameworks:
    - Vue.js: advanced
    - React: advanced
    - Node.js: medium
    - Django: medium
    - NestJs: beginner
    - Hasura: advanced
  tools:
    - Git: advanced
    - Docker: medium
    - Github Actions: medium
    - Tmux: beginner
    - NeoVim: beginner
  databases:
    - PostgreSQL: medium
    - Mongodb: medium
    - Firestore: medium
education:
  - institution: Addis Ababa University
    study: Bsc. Software Engineering
    location: "Addis Ababa, Ethiopia"
    start: "September 2016"
    end: "October 2021"
    gpa: 3.57
    description:
      - One of the top universities in Africa
      - Graduated with Great Distinction 
projects:
  - name: Meal Time
    repo: MealTime
    description: A meal planning and recipe management app with many features that make meal planning a breeze.
    banner:
      branch: main
      path: assets/banner.png
      tech:
      - Next.js
      - Spring Boot
      - Keycloak
      - Mysql
      - Docker
      - Python
  - name: Match The Tiles
    repo: MatchTheTilesGame
    description: A puzzle game where you must find and eliminate pairs of identical tiles by flipping them over, aiming to clear the entire board.
    banner:
      branch: main
      path: screenshots/banner.png
      tech:
      - Javascript
      - HTML
      - CSS
  - name: Crypto Track
    repo: CryptoTrack
    description: Track your Cryptocurrencies and get instant email notification whenever they change
    banner:
      branch: main
      path: banner.png
      tech:
      - Supabase
      - React
      - Courier
  - name: The Classroom
    repo: TheClassroom
    description: A Learning Management system
    banner:
      branch: main
      path: banner.png
    tech:
      - Hasura
      - React
      - Auth0
      - GraphQL
  - name:  HTML Canvas Image Watermarker
    repo: HTMLCanvasImageWatermarker
    description: Image Watermarking Tool built using HTML Canvas.
    banner:
      branch: main
      path: banner.png
    tech:
      - JavaScript
      - Vite
      - Bootstrap
  - name: Dash Store
    repo: DashStore
    description: Web application for creating an online storefront
    banner:
      branch: main
      path: banner.png
      tech:
      - Laravel
      - Blade
      - Tailwind CSS
  - name: Peer Notes
    repo: peernotes
    description: A web application for High School students to share school notes with other peers
    banner:
      branch: main
      path: assets/banner.png
    tech:
      - Hasura
      - React
      - Auth0
      - Algolia
      - Docker
      - Github Actions
      - GraphQL
  - name: Keywrite
    repo: keywrite
    description: A Javascript library for creating custom input methods for typing non-Latin scripts on a standard keyboard
    banner:
      branch: main
      path: logo/banner.png
    tech:
      - TypeScript
      - Yarn Workspace
      - Lerna
      - GitHub Actions
  - name: School Location Analysis Tool
    repo: gis-school-analysis-tool
    description: a GIS application to locate potential locations for public school construction in Addis Ababa, Ethiopia.
    banner:
      branch: master
      path: banner.png
    tech:
      - GeoDjango
      - PostGIS
      - Bootstrap
      - LeafletJs
      - Heroku
      - Docker
  - name: Pic Share
    repo: pic-share
    description: WebRTC-based P2P image-sharing web application
    banner:
      branch: master
      path: img/banner.png
    tech:
      - WebRTC
      - React
      - NodeJs
  - name:  Link In Bio Tool
    repo: LinkInBio
    description: Link In Bio tool made with Cloudflare Workers and KV.
    banner:
      branch: main
      path: banner.png
    tech:
      - Typescript
      - Cloudflare Workers
      - Cloudflare KV
  - name: Amharic Proverbs
    repo: AmharicProverbs
    description: Web application to access Amharic proverbs from the Amharic Proverbs API
    banner:
      branch: main
      path: banner.png
    tech:
      - Vue3
      - Bootstrap
      - Vite
      - REST API
  - name:  Kesar Cipher
    repo: KesarCipher
    description: Implementation of the Caesar Cipher encryption algorithm that works with the Ge'ez Alphabet
    banner:
      branch: main
      path: banner.png
    tech:
      - JavaScript
      - Vite
      - Tailwind CSS
  - name:  Amharic Proverbs API
    repo: AmharicProverbsAPI
    description: API for accessing a growing list of Amharic Proverbs
    banner:
      branch: main
      path: banner.png
    tech:
      - NestJs
      - MongoDB
      - Heroku
