name: Update README
on:
    push:
      branches:
        - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Install
            run: |
              cd readme-generator
              yarn
          - name: Generate readme
            run: |
              node ./readme-generator/index.js -c ./config.yaml -o ./README.md
          - name: Commit changes
            uses: EndBug/add-and-commit@v9
            with:
              committer_name: README Generator
              message: 'auto-generate README'
              add: 'README.md'


